Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
  config.vm.synced_folder ".", "/var/www/html"
  config.vm.define "MusicbrowserAzem"
  config.vm.hostname = "MusicbrowserAzem"
  config.vm.provision :file, source:"index.php", destination: "/tmp/index.php"
  config.vm.provision :file, source:"Spaceship.mp3", destination: "/tmp/Spaceship.mp3"
  config.vm.provider "virtualbox" do |vb|
  vb.name = "MusicbrowserAzem"
  vb.memory = "5024"
end
config.vm.provision "shell", inline: <<-SHELL
  # Packages vom lokalen Server holen
  # sudo sed -i -e"1i deb {{config.server}}/apt-mirror/mirror/archive.ubuntu.com/ubuntu xenial main restricted" /etc/apt/sources.list
  sudo apt-get update
  sudo apt-get -y install apache2
  # sudo apt-get -y install php libapache2-mod-php php-mcrypt php-mysql
  sudo systemctl restart apache2
  sudo apt-get -y install unzip
  sudo mkdir /musicbrowser
  cd /musicbrowser
  # sudo apt-get install git
  sudo git clone git://github.com/henrik242/musicbrowser.git
  cd /var/www
  sudo wget https://github.com/henrik242/musicbrowser/archive/master.zip
  sudo unzip master.zip
  cd musicbrowser-master/src/
  sudo cp /tmp/index.php .
  cd
  cd /musicbrowser
  sudo cp /tmp/Spaceship.mp3 .
SHELL



end
