Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu1804"
    config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    config.vm.synced_folder ".", "/var/www/html"
    config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
end
#test#
config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get upgrade
    apt-get install -y apache2
SHELL
end
